### ISSUE TITLE
Add old logo to this github for history 

### ISSUE THREAD

**Issue by gghezzo** [OSLC/logo#1]
We should add the OSLC-logo_5-serives.zip and mark it as legacy. This will allow us to remove it from open-services.net wiki while avoid losing it. 
1. Upload it somewhere
2. Update the Readme in this repository to link to it and note it is legacy. 
Thank you, 
Ginny

**Comment by leereamsnyder** [comment]
here ya go: https://github.com/OSLC/logo/blob/legacy-logo/OSLC-logo-legacy-pre-2014.zip?raw=true
